from __future__ import annotations

import argparse
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
README = ROOT / "README.md"
SVG_NAMESPACE = "{http://www.w3.org/2000/svg}"


def fail(message: str) -> None:
    raise AssertionError(message)


def validate_svg(path: pathlib.Path) -> None:
    root = ET.parse(path).getroot()
    if root.get("role") != "img":
        fail(f"Missing role=img: {path.relative_to(ROOT)}")
    if not (root.get("aria-label") or root.get("aria-labelledby")):
        fail(f"Missing accessible name: {path.relative_to(ROOT)}")

    if path.name.startswith("profile-"):
        labelled_by = set((root.get("aria-labelledby") or "").split())
        ids = {element.get("id") for element in root.iter() if element.get("id")}
        if not {"title", "desc"}.issubset(ids):
            fail(f"Missing title/desc: {path.relative_to(ROOT)}")
        if not {"title", "desc"}.issubset(labelled_by):
            fail(
                f"aria-labelledby must reference title and desc: {path.relative_to(ROOT)}"
            )
        title = root.find(f"{SVG_NAMESPACE}title")
        description = root.find(f"{SVG_NAMESPACE}desc")
        if title is None or not (title.text or "").strip():
            fail(f"Empty title: {path.relative_to(ROOT)}")
        if description is None or not (description.text or "").strip():
            fail(f"Empty description: {path.relative_to(ROOT)}")


def validate_readme() -> None:
    content = README.read_text(encoding="utf-8")
    local_references = re.findall(
        r'(?:src|srcset)="(\./assets/[^" ]+)', content
    )
    if not local_references:
        fail("README does not reference any local profile assets")

    missing = [
        reference
        for reference in local_references
        if not (ROOT / reference.removeprefix("./")).is_file()
    ]
    if missing:
        fail(f"Missing README assets: {missing}")

    required_sections = (
        "engineering-focus",
        "selected-work",
        "engineering-snapshot",
        "connect",
    )
    for section in required_sections:
        if f'id="{section}"' not in content:
            fail(f"Missing README section anchor: {section}")

    if "safepack" in content.lower():
        fail("Excluded repository found in README")
    if "img.shields.io/github/" in content:
        fail("Dynamic GitHub metrics must be generated by repository workflows")


def validate_workflows() -> None:
    workflow_paths = sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    if not workflow_paths:
        fail("No GitHub Actions workflows found")

    action_pattern = re.compile(r"^\s*uses:\s*([^\s#]+)", re.MULTILINE)
    for path in workflow_paths:
        content = path.read_text(encoding="utf-8")
        if "permissions:" not in content:
            fail(f"Workflow does not declare permissions: {path.relative_to(ROOT)}")
        if "timeout-minutes:" not in content:
            fail(f"Workflow job has no timeout: {path.relative_to(ROOT)}")

        for action in action_pattern.findall(content):
            if action.startswith("./"):
                continue
            if "@" not in action:
                fail(f"Action has no immutable reference: {action}")
            reference = action.rsplit("@", 1)[1]
            if not re.fullmatch(r"[0-9a-f]{40}", reference):
                fail(f"Action is not pinned to a full commit SHA: {action}")

    metrics_workflow = (
        ROOT / ".github" / "workflows" / "profile-metrics.yml"
    ).read_text(encoding="utf-8")
    if "GH_TOKEN: ${{ github.token }}" not in metrics_workflow:
        fail("Profile metrics workflow must use the scoped GITHUB_TOKEN")
    if "PROFILE_FEATURED_REPOSITORIES: ${{ vars.PROFILE_FEATURED_REPOSITORIES }}" not in metrics_workflow:
        fail("Profile metrics workflow must expose optional repository preferences")


def validate_no_dynamic_hardcoding() -> None:
    inspected_paths = [
        ROOT / "scripts" / "generate-profile-metrics.mjs",
        ROOT / "scripts" / "lib" / "profile-data.mjs",
        ROOT / ".github" / "workflows" / "profile-metrics.yml",
    ]
    content = "\n".join(path.read_text(encoding="utf-8") for path in inspected_paths)

    forbidden = (
        "PROFILE_PRIVATE_REPOSITORIES",
        "PROFILE_PRIVATE_TOKEN_CONFIGURED",
        "HRS-code-public",
        "folderverse-3d",
        "Fca-Horizon-Remastered",
        "Global_Horizon",
    )
    for value in forbidden:
        if value in content:
            fail(f"Dynamic profile generator contains hardcoded value: {value}")


def validate_required_files() -> None:
    required = (
        README,
        ASSETS / "profile-header.svg",
        ASSETS / "profile-metrics.svg",
        ASSETS / "profile-metrics-mobile.svg",
        ASSETS / "profile-footer.svg",
        ROOT / "package.json",
        ROOT / "scripts" / "generate-profile-metrics.mjs",
        ROOT / "scripts" / "lib" / "profile-data.mjs",
        ROOT / "tests" / "profile-data.test.mjs",
    )
    missing = [str(path.relative_to(ROOT)) for path in required if not path.is_file()]
    if missing:
        fail(f"Missing required profile files: {missing}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate profile README and SVG assets")
    parser.add_argument(
        "--generated-dir",
        type=pathlib.Path,
        help="Optional directory containing freshly generated SVG previews",
    )
    arguments = parser.parse_args()

    validate_required_files()
    validate_readme()
    validate_workflows()
    validate_no_dynamic_hardcoding()

    svg_paths = sorted(ASSETS.rglob("*.svg"))
    if arguments.generated_dir:
        generated_dir = arguments.generated_dir.resolve()
        generated_paths = sorted(generated_dir.rglob("*.svg"))
        if len(generated_paths) < 2:
            fail(f"Expected generated desktop and mobile SVGs in {generated_dir}")
        svg_paths.extend(generated_paths)

    for path in svg_paths:
        validate_svg(path)

    print(
        f"Validated README, dynamic configuration, and {len(svg_paths)} accessible SVG assets."
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AssertionError, ET.ParseError) as error:
        print(f"Validation failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
